version: '3'

services:
  elastic_search:
    container_name: myelasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - elasticsearch_net
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
    depends_on:
      - elastic_search
    environment:
      - "SERVER_NAME=MyKibana"
      - ELASTICSEARCH_HOSTS="http://myelasticsearch:9200"
    networks:
      - elasticsearch_net

volumes:
  elasticsearch_data:
    driver: local

networks:
  elasticsearch_net:
